FROM alpine:latest

RUN apk update && \
    apk add nginx && \
    rm -rf /var/cache/apk/*

RUN mkdir -p /var/www/localhost/htdocs && \
    echo "<h1>Application Deployed via Terraform IaC!</h1>" \
    > /var/www/localhost/htdocs/index.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]