FROM alpine:latest

RUN apk update && apk add nginx && rm -rf /var/cache/apk/*

RUN mkdir -p /var/www/localhost/htdocs

COPY index.html /var/www/localhost/htdocs/index.html

RUN echo 'server {' > /etc/nginx/http.d/default.conf && \
    echo '  listen 80 default_server;' >> /etc/nginx/http.d/default.conf && \
    echo '  listen [::]:80 default_server;' >> /etc/nginx/http.d/default.conf && \
    echo '  server_name _;' >> /etc/nginx/http.d/default.conf && \
    echo '  root /var/www/localhost/htdocs;' >> /etc/nginx/http.d/default.conf && \
    echo '  location / {' >> /etc/nginx/http.d/default.conf && \
    echo '    try_files $uri $uri/ =404;' >> /etc/nginx/http.d/default.conf && \
    echo '  }' >> /etc/nginx/http.d/default.conf && \
    echo '}' >> /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
