name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: >-
          --privileged
          -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./tp-iac-local

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./tp-iac-local
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./tp-iac-local
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
